# Generated by Django 5.0.6 on 2024-07-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cabanas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencabana',
            name='cabana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='admin_cabanas.cabana'),
        ),
    ]
