# Generated by Django 5.0.6 on 2024-07-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='numero_estrellas',
            field=models.IntegerField(default=0),
        ),
    ]
