# Generated by Django 5.0.6 on 2024-07-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='fecha_fin',
            field=models.DateField(verbose_name='Selecciona la fecha de salida'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Selecciona la fecha de llegada'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='metodo_pago',
            field=models.CharField(max_length=50, verbose_name='Selecciona el metodo de pago'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promocion', verbose_name='Selecciona una promoción'),
        ),
    ]
