# Generated by Django 5.0.6 on 2024-07-31 01:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', ckeditor.fields.RichTextField(verbose_name='Comentario')),
            ],
        ),
    ]
