# Generated by Django 5.0.6 on 2024-07-17 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cabanas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=300)),
                ('numero_estrellas', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True, null=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cabanas.cabana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-creado'],
            },
        ),
    ]
